### ISSUE TITLE
Updating pycoreaudio to python3 

### ISSUE THREAD

**Issue by shakfu** [larsimmisch/pycoreaudio#1]
Hi @larsimmisch 

I've updated the pycoreaudio extension to python3 c-api in my [fork](https://github.com/shakfu/pycoreaudio). My original intent was to create a cython wrapper, but I started fixing the original extension to the extent I could.

There are still a  bunch of deprecations, and it certainly needs more testing and polish but ... would you be interested in a PR and to update this extension to 3 properly? It would be a shame not to return this nice project to usefulness to python3 users...

**Comment by larsimmisch** [comment]
Hi @shakfu,

Sure, open a PR! I can't promise much help, but even nitpicky PR reviews can be useful and maybe I can spot some depreciation errors quickly.

**Comment by shakfu** [comment]
Thanks for your reply... I will make a PR soonish... fyi, the current deprecations / warnings are:

```c++
coreaudio.c:339:9: warning: 'CloseComponent' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
        CloseComponent(obj->instance);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:594:1: note: 'CloseComponent' has been explicitly marked deprecated here
CloseComponent(ComponentInstance aComponentInstance)          __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
^
coreaudio.c:636:13: warning: 'FindNextComponent' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
        c = FindNextComponent(NULL, &componentDescription->desc);
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:470:1: note: 'FindNextComponent' has been explicitly marked deprecated here
FindNextComponent(
^
coreaudio.c:638:13: warning: 'FindNextComponent' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
        c = FindNextComponent(component->component,
            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:470:1: note: 'FindNextComponent' has been explicitly marked deprecated here
FindNextComponent(
^
coreaudio.c:665:10: warning: 'OpenAComponent' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
    rc = OpenAComponent(component->component, &au);
         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Components.h:560:1: note: 'OpenAComponent' has been explicitly marked deprecated here
OpenAComponent(
^
coreaudio.c:708:5: warning: 'PyEval_InitThreads' is deprecated [-Wdeprecated-declarations]
    PyEval_InitThreads();
    ^
/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/ceval.h:132:1: note: 'PyEval_InitThreads' has been explicitly marked deprecated here
Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
^
/opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/include/python3.12/pyport.h:317:54: note: expanded from macro 'Py_DEPRECATED'
#define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                     ^
5 warnings generated.
```

**Comment by larsimmisch** [comment]
Hmm. The `PyEval_InitThreads` depreciation looks easy enough, but it seems Apple has deprecated the entire `Component` API.

**Comment by shakfu** [comment]
@larsimmisch fyi, I've committed a clean PR without all the stillborn cython cruft: [PR2](https://github.com/larsimmisch/pycoreaudio/pull/2)

**Comment by shakfu** [comment]
@larsimmisch After some research and finding a [rosetta stone](https://github.com/hydrogen-music/hydrogen/commit/6e510eba13b3d05723bf732af7727ed3cedfabb3) of relevant fixes, I managed to get rid of all the warnings (if I comment out `PyEval_InitThreads`)

I'd appreciate further help on this to get it back to its working state.

**Comment by larsimmisch** [comment]
> After some research and finding a [rosetta stone](https://github.com/hydrogen-music/hydrogen/commit/6e510eba13b3d05723bf732af7727ed3cedfabb3) of relevant fixes, I managed to get rid of all the warnings (if I comment out PyEval_InitThreads)

Nice! I'll try to take a look tomorrow why play.py isn't working in the new version. It did work in the old one, right?

About the `PyEval_InitThreads`, something like this should be backwards compatible:

```
#if PY_VERSION_HEX < 0x03090000
    PyEval_InitThreads();
#endif
```

**Comment by larsimmisch** [comment]
FWIW, I did a very cursory code review and nothing was standing out, but I remember that getting the first version to work was tricky.

**Comment by shakfu** [comment]
@larsimmisch 

> Nice! I'll try to take a look tomorrow why play.py isn't working in the new version. It did work in the old one, right?

Thanks. I'm not sure since the earlier code was not working for me on python3.

> FWIW, I did a very cursory code review and nothing was standing out, but I remember that getting the first version to work was tricky.

One thing is for sure, for a company which can afford to have decent documentation for its public api, Apple's docs are  absolutely terrible and far worse than decent open-source code. You really have to read the headers, since the published web docs just provide identifier... even functions are missing parameter type info which would be provided in doxygen for example.

To make matter's worse, there are no official migration guides when APIs are deprecated.

Anyway (rant over) let's see where this goes... it would be nice to get this demo working somehow ...

**Comment by shakfu** [comment]
[this](https://bastibe.de/2017-06-17-audio-apis-coreaudio.html) post from 2017 sounds familiar.from the author of [SoundCard](https://github.com/bastibe/SoundCard)

**Comment by larsimmisch** [comment]
> It is known for its high performance, low latency, and horrible documentation.

True. I was relieved to read that and see that we are not alone.

**Comment by larsimmisch** [comment]
Did you try out [SoundCard](https://github.com/bastibe/SoundCard)? If that works, you’d have something to compare to.

**Comment by shakfu** [comment]
> Did you try out [SoundCard](https://github.com/bastibe/SoundCard)? If that works, you’d have something to compare to.

Yes, I has a look at the code..  It's very helpful indeed.

**Comment by larsimmisch** [comment]
This example is also interesting: https://github.com/joostvdm/ausine/blob/main/ausine.py
